### ISSUE TITLE
Move matplotlib out of core module requires

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/wikimap#5]
Matplotlib is a huge dependency. Installing Wikimap takes over 5 minutes. It would be great if we could move the dependency on matplotlib outside of the wikimap module into a separate script. I feel like rendering graphs is not as common a use case for other projects that depend on wikimap.

Flagging for later.

**Comment by michaelsilver** [comment]
I created a new branch called `matplotlib` for this issue. Indeed, matplotlib is a huge dependency. At master 3e27c42, Travis took 3 min 9 sec. The same exact code, minus the matplotlib dependency at matplotlib  c047884, Travis took 1 min 41 sec, or about half the time.

As you said, I only use the matplotlib module to graph, as seen in the [iPython notebook](https://github.com/infolab-csail/wikimap/blob/master/WikiMap%20Analysis.ipynb). Maybe I should just leave matplotlib out of the `setup.py` and just have a note in either the README or iPython notebook that if you want to graph, you must install matplotlib youself. What do you think?
